language: generic
sudo: required
dist: trusty

os:
- linux

env:
- LAZ_VER=1.8.4

install:
- sudo add-apt-repository ppa:jonathonf/binutils -y
- sudo apt-get update -y
- sudo apt-get install binutils -y
- ./travis-lazarus/.travis.install.py

script:
- lazbuild source/TatraDAS.lpi
